# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/stapril/hardware/CDC/ip/async_fifo/async_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_fifo || ORIG_REF_NAME==async_fifo} -quiet] -quiet
